--- 
# after_success: 
#   - "npm run deploy"
branches: 
  only: 
    - master
    - stable
cache: 
  directories: 
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: build
  keep_history: true
 
  on:
    branch: master
dist: trusty
env: 
  global: 
    - TIMEOUT=1000D
language: node_js
node_js: 
  - 8
script: 
  - "npm run test --watchAll"
  - "npm run build"
sudo: false
